---
- name: Example playbook
  hosts: all
  vars:
    'db_password: "SuperSecret123"
    'api_token: "XYZ987"

  tasks:
    - name: Create admin
      user:
        'name: admin'
        'password: "P@ssw0rd!"
