- name: Test hard-coded password detection
  hosts: localhost
  gather_facts: false

  tasks:
    - name: MySQL user with hard-coded password
      community.mysql.mysql_user:
        name: admin
        password: "P@ssw0rd123"
        state: present

    - name: File with hard-coded password
      ansible.builtin.copy:
        dest: /tmp/secret.txt
        content: "DB password is P@ssw0rd123"
