---
# playbook.yml
# Example Ansible playbook for testing ansible-lint custom rule

- hosts: all
  # name: "Example Playbook"   # Uncomment this line to satisfy the custom rule
  gather_facts: false

  tasks:
    - name: Ensure /tmp/testfile exists
      file:
        path: /tmp/testfile
        state: touch

    - name: Print a message
      debug:
        msg: "Hello, Ansible Lint!"
