---
- name: Test Playbook for Hard-Coded Passwords
  hosts: localhost
  gather_facts: false

  tasks:
    - name: MySQL user with hard-coded password
      community.mysql.mysql_user:
        name: admin
        password: "P@ssw0rd123"
        priv: "mydb.*:ALL"
        state: present

    - name: PostgreSQL user with hard-coded password
      community.postgresql.postgresql_user:
        name: pgadmin
        password: "pgP@ss456"
        role_attr_flags: LOGIN
        state: present

    - name: Create a file with hard-coded password
      ansible.builtin.copy:
        dest: "/tmp/secret.txt"
        content: "DB password is mySecret123"
        mode: '0600'

    - name: Inline content without password variable
      ansible.builtin.copy:
        dest: "/tmp/okfile.txt"
        content: "No passwords here"
        mode: '0600'
