---
- name: Test playbook with hardcoded passwords
  hosts: all
  vars:
    db_password: "MySecret123"
    api_token: "XYZ987"

  tasks:
    - name: Create user
      user:
        name: admin
        password: hardcoded!
