---
- name: Sample playbook with hard-coded passwords
  hosts: all
  become: yes

  vars:
    db_user: "admin"
    db_password: "P@ssw0rd123"   # Hard-coded password (intentional)

  tasks:
    - name: Create database user with hard-coded password
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "mydb.*:ALL"
        state: present

    - name: Create a file with a hard-coded password
      copy:
        dest: "/tmp/secret.txt"
        content: "DB password is {{ db_password }}"
        mode: '0600'
