---
- name: Test playbook for hardcoded passwords
  hosts: localhost
  gather_facts: false

  vars:
    safe_password: "{{ vault_db_password }}"   # ✅ Will NOT trigger
    password: "mySuperSecret123"       # ❌ Will trigger CUSTOM001

  tasks:
    - name: Task with templated password
      user:
        name: "templated_user"
        password: "{{ vault_db_password }}"    # ✅ Will NOT trigger

    - name: Task with hardcoded password
      user:
        name: "admin"
        passwd: "Admin123!"                  # ❌ Will trigger CUSTOM001

    - name: Task with hardcoded secret token
      uri:
        url: "https://example.com/api"
        headers:
          Authorization: "Bearer mysecrettoken" # ❌ Will trigger CUSTOM001

    - name: Task with vault reference
      user:
        name: "vault_user"
        password: "!vault | ..."               # ✅ Will NOT trigger
