---
- name: Write config file
  hosts: all
  tasks:
    - name: Create database config
      copy:
        dest: /etc/app/db.conf
        content: |
          username=appuser
          password=myDBpass123  # <-- Hardcoded password
