# playbooks/deploy_app.yml
- name: Deploy example app (insecure: hardcoded passwords)
  hosts: app_servers
  become: yes
  vars:
    db_user: "app_user"
    db_password: "Test123"   # <-- Hardcoded secret
  tasks:
    - name: Ensure app directory exists
      file:
        path: /opt/example_app
        state: directory
        owner: "{{ db_user }}"
        mode: '0755'

    - name: Create database user (example)
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "example_db.*:ALL"
        state: present
      delegate_to: db.example.internal
