- hosts: localhost
  gather_facts: false
  vars:
    secret: "hardcoded123"
  tasks:
    - name: Example task with hardcoded password
      user:
        name: testuser
        password: "supersecret"

    - name: Task with nested vars
      debug:
        msg:
          inner:
            passwd: "nestedsecret"
