- name: Example playbook with hardcoded password
  hosts: localhost
  vars:
    db_password: mySecret123
    api_key: "12345-ABCDE"
  tasks:
    - name: Dummy task
      debug:
        msg: "Hello World"
