- hosts: localhost
  gather_facts: false
  tasks:
    - name: Hardcoded password
      ansible.builtin.user:
        name: testuser
        password: "supersecret"

    - name: Nested password
      ansible.builtin.debug:
        msg:
          inner:
            passwd: "nestedsecret"
