- hosts: localhost
  gather_facts: false
  tasks:
    - name: Hardcoded password
      user:
        name: testuser
        password: "supersecret"

    - name: Nested password
      debug:
        msg:
          inner:
            passwd: "nestedsecret"
