- hosts: localhost
  gather_facts: false
  vars:
    my_secret: "hardcoded123"
  tasks:
    - name: Hardcoded password task
      user:
        name: testuser
        password: "supersecret"

    - name: Nested password
      debug:
        msg:
          inner:
            passwd: "nestedsecret"
