name: Inventory Update Pipeline

# Trigger when a user modifies inventory files or manually triggers workflow
on:
  push:
    paths:
      - 'inventory/**'        # only triggers if files under inventory/ change
  workflow_dispatch:          # allows manual triggering

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    outputs:
      approval_id: ${{ steps.generate.outputs.approval_id }}
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generate a unique approval ID
      - name: Generate Approval ID
        id: generate
        run: |
          APPROVAL_ID=$(uuidgen)
          echo "approval_id=$APPROVAL_ID" >> $GITHUB_OUTPUT
          echo "Generated approval ID: $APPROVAL_ID"

      # 3. Define allowed hostnames (or app IDs)
      - name: Define Allowed Hosts
        id: define_hosts
        run: |
          HOSTNAMES=("inventory.example.com" "orders.example.com" "shipping.example.com")
          echo "HOSTNAMES=${HOSTNAMES[@]}" >> $GITHUB_ENV
          echo "Allowed hosts: ${HOSTNAMES[@]}"

      # 4. Validate modified inventory against allowed hosts
      - name: Validate Inventory
        run: |
          echo "Validating modified inventory..."
          # Example inventory content from user modification
          INVENTORY_HOSTS=("inventory.example.com" "unknown.example.com")
          INVALID_HOSTS=()
          for host in "${INVENTORY_HOSTS[@]}"; do
            if [[ ! " ${HOSTNAMES[@]} " =~ " ${host} " ]]; then
              INVALID_HOSTS+=("$host")
            fi
          done

          if [ ${#INVALID_HOSTS[@]} -gt 0 ]; then
            echo "Error: Inventory contains invalid hosts: ${INVALID_HOSTS[@]}"
            exit 1
          fi
          echo "Inventory validated successfully."

  admin-approval:
    runs-on: ubuntu-latest
    needs: update-inventory
    environment: Inventory Approval   # workflow pauses here for admin approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Approval Details
        run: |
          echo "Admin approval required for inventory update."
          echo "Approval ID: ${{ needs.update-inventory.outputs.approval_id }}"
          echo "Validated Hosts: ${{ env.HOSTNAMES }}"

  deploy-inventory:
    runs-on: ubuntu-latest
    needs: admin-approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Inventory
        run: |
          echo "Deploying inventory changes to hosts: ${{ env.HOSTNAMES }}"
          # Add your real deployment commands here
